### PR TITLE
updated files to latest skeleton

### PR DESCRIPTION
**Pull request by rosesyrett**
A PR to add in some recent pip skeleton things, like:

- getting rid of setup.cfg and setup.py, replacing with pyproject.toml
- updated documentation structure

I have not adopted the new dockerfile structure as it seemed to fail when I tried to use it. Also, I do distinguish between the dockerfile I use in production and for my vscode container, whereas it seems the new pip skeleton does not. The new devcontainer.json looks really good but I just cannot get it to work for some reason.

### CODE REVIEW

**Comment by rosesyrett** [comment]
One thing that confuses me at the moment is _version.py vs _version_git.py which has been in use historically. My repo uses the _version_git to figure out which version it should set as a default in the helm chart. I need to investigate if I can just replace _version_git with _version easily.

**Comment by garryod** [comment]
> One thing that confuses me at the moment is _version.py vs _version_git.py which has been in use historically. My repo uses the _version_git to figure out which version it should set as a default in the helm chart. I need to investigate if I can just replace _version_git with _version easily.

`_version_git.py` has actually been replaced with `setuptools_scm` which generates `_version.py` as an artefact. It should be a drop in replacement provided you're not calling into any of the functions of `_version_git` (which would be odd)

**Comment by rosesyrett** [comment]
I'm currently struggling to figure out why my container is not building...

**Comment by garryod** [comment]
> I'm currently struggling to figure out why my container is not building...

During the CI, the job tries to run `uvicorn src.diffcalc_api.server:app --host 0.0.0.0 --version` (with the first 4 terms from the Dockerfile CMD and the last from the exec parameters. Ofcourse there is no `--version` option for uvicorn. I get around this by having my binary delegate to uvicorn in my `__main__`. See [papermill_service](https://github.com/garryod/papermill_service/blob/main/src/papermill_service/__main__.py) for an example.

**Review by joeshannon — APPROVED** [review]
I see some of the checks failed. Is that ok for now?

**Comment by rosesyrett** [comment]
I'll have a look and see what's going on - shouldn't be failing!

**Pull request merged**
